"""followers

Revision ID: 19613206aaba
Revises: 2565a8fbf8c3
Create Date: 2023-02-16 18:17:21.548535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19613206aaba'
down_revision = '2565a8fbf8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
